services:

  # ── API Gateway ──────────────────────────────────────────────────
  # Single acces point for user, inventory and auth
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8000"          # API gateway exposed port
    depends_on:
      - auth-service
      - inventory-service
      # - ai-service
    networks:
      - pantryly-net
    restart: unless-stopped

  # ── Auth Service ─────────────────────────────────────────────────
  # Signup + JWT + validation
  auth-service:
    build: ./microservices/auth-service
    container_name: auth-service
    env_file:
      - ./microservices/auth-service/.env
    networks:
      - pantryly-net
    restart: unless-stopped
    # No ports, it is accessible only from internal net

  # ── Inventory Service ────────────────────────────────────────────
  # CRUD products endpoint
  inventory-service:
    build: ./microservices/inventory-service
    container_name: inventory-service
    env_file:
      - ./microservices/inventory-service/.env
    networks:
      - pantryly-net
    restart: unless-stopped

  # ── AI Service ───────────────────────────────────────────────────
  # AI service for receipe generation or product categorization
  ai-service:
    build: ./microservices/ai-service
    container_name: ai-service
    env_file:
      - ./microservices/ai-service/.env
    networks:
      - pantryly-net
    restart: unless-stopped
    ports:
      - "8081:8000"  
# Internal network
networks:
  pantryly-net:
    driver: bridge
