FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:0.7.2 /uv /uvx /bin/

WORKDIR /app

COPY requirements.txt .

RUN uv pip install --system --no-cache -r requirements.txt

COPY . .

CMD ["uvicorn" , "app.main:app" , "--host", "0.0.0.0", "--port", "8000"]
